version: 0.2.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU

before_build:
- cmd: nuget restore
- cmd: nuget install -ExcludeVersion ILMerge

assembly_info:
  patch: true
  file: '**\AssemblyInfo.cs'
  assembly_version: $(appveyor_build_version)
  assembly_file_version: $(appveyor_build_version)
  assembly_informational_version: $(appveyor_build_version)

build:
  project: Elite-Log-Agent.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: normal  
  parallel: true

after_build:
- cmd: mkdir bin\Release
- cmd: ILMerge\tools\ilmerge.exe /wildcards /out:EliteLogAgent.exe TrayAgent\bin\Release\TrayAgent.exe TrayAgent\bin\Release\*.dll
- cmd: msbuild Elite-Log-Agent.sln /target:Publish /p:Configuration=Release /p:Platform="Any CPU" /p:PublishProfile=Release /property:ApplicationVersion="$env:APPVEYOR_BUILD_VERSION"

artifacts: 
- path: EliteLogAgent.exe
  name: single-executable
- path: TrayAgent\bin\Release\*
  name: trayagent-binaries
- path: bin\Release\app.publish\*
  name: published

deploy:
- provider: GitHub
  on:
    branch: master;develop
  tag: release-$(appveyor_build_version)
  release: $(appveyor_build_version)
  auth_token:
    secure: cMLUYhjbQt3D197vZwjRci/zvwagN86wEZtJzX1L3apKsslN44Uo6TUo54vIQVg6
  artifact: single-executable
  draft: true
  force_update: true